name: dinobase
description: A dinosaur database.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 0.0.1

environment:
  sdk: '>=2.19.4 <3.0.0'

dependencies:
  flex_color_scheme: ^6.1.2
  flutter:
    sdk: flutter
  flutter_launcher_icons: ^0.12.0
  flutter_riverpod: ^2.3.2
  recase: ^4.1.0
  riverpod: ^2.3.2
  riverpod_annotation: ^2.0.2

dev_dependencies:
  build_runner: ^2.3.3
  custom_lint: ^0.3.2
  flutter_lints: ^2.0.1
  riverpod_generator: ^2.1.4
  riverpod_lint: ^1.1.6

flutter:
  uses-material-design: true

  assets:
    - assets/images/backgrounds/
    - assets/images/dinosaurs/
    - assets/images/icons/

  fonts:
    - family: Merienda
      fonts:
        - asset: assets/fonts/Merienda/static/Merienda-Regular.ttf
    - family: DinoSauce
      fonts:
        - asset: assets/fonts/dinosauce/DinosauceFont-Regular.ttf
    - family: Erasaur
      fonts:
        - asset: assets/fonts/erasaur/Erasaur-wjZ9.otf
